apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: j5kpnqt6h-nodejs 
  janus-idp.io/tekton: j5kpnqt6h-nodejs
  backstage.io/kubernetes-id: j5kpnqt6h-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j5kpnqt6h-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  